dcos/examples

- 1.8/scale/README.md
- 1.8/scale/scale-demo-cloudformation.json
- 1.8/scale/scale-demo-policy.json
- 1.8/scale/scale-init.sh
This pull request is at the request of @ryadav88 to document the use and setup of Scale package under review for Universe acceptance. See https://github.com/mesosphere/universe/pull/791.
> Scale tutorial documentation

- 1.8/nexus/README.md
Sorry, I just saw that there's a copy/paste error, which is fixed with this commit.
> Fix copy/paste typo for Nexus example

- 1.8/linkerd/README.md
depends on https://github.com/mesosphere/universe/pull/855
> additional linkerd instructions for enterprise

- 1.8/ceph/README.md
just an IP address change -- hence the request not to fork&merge
> correct example HOST_NETWORK to reflect the rest of the example.

- 1.8/ceph/README.md
clarified with the framework's author on the correct uninstall procedure, modifying it here.
> correct uninstall procedure

- 1.8/ceph/README.md
according to
https://github.com/mesosphere/universe/pull/885
and
https://github.com/mesosphere/universe/pull/884
CC: @ryadav88 
Tested and working. Will correct any erratas following feedback.
> Ceph v0.2 plus Ceph Dashboard 0.1

- 1.8/vamp/README.md
- 1.8/vamp/vamp-config.json
This completed the Universe PR to have Vamp 0.9.2 added to DC/OS: https://github.com/mesosphere/universe/pull/891
> Update logstash to logstash-host to reflect new Universe package

- 1.8/ceph/README.md
> update ceph logo

- 1.8/linkerd/README.md
depends on https://github.com/mesosphere/universe/pull/916
> update linkerd-viz instructions for 0.0.7 release

- 1.8/ceph/README.md
> update ceph logo location

- 1.8/riak/README.md
- README.md
Part of the work for mesosphere/universe#703
> Add Riak getting-started doc

- 1.8/vamp/README.md
- 1.8/vamp/vamp-config.json
To match the new package under https://github.com/mesosphere/universe/pull/969
> Vamp release 0.9.3

- 1.8/ceph/README.md
doesn't look good on the side of the tiny ceph logo.
> remove dc/os logo

- clair/1.8/README.md
- clair/1.9/README.md
- clair/README.md
This adds the example for the upcoming Clair Universe package. Please don't merge yet.
> Add Clair example

- kong/1.9/README.md
Docs updated to sync with https://github.com/mesosphere/universe/pull/1225
> Remove reference to VIPs

- cockroachdb/1.9/README.md
- cockroachdb/README.md
@springle @LakeCarrot @a-robinson
> Add Cockroachdb example

- kong/1.9/README.md
for https://github.com/mesosphere/universe/pull/1355 update.
> support for Kong v0.11.0

- tensorflow/1.10/README.md
@joerg84 I have tried to update the TensorFlow example so that it is something that someone can follow step-by-step. I'm not sure if this is the style that is desired.
@klueska could you or @springle also take a look?
> Update TensorFlow example

- beakerx/1.10/README.md
- beakerx/README.md
Examples how to install, configure and use the BeakerX universe package
> Initial BeakerX examples

- beakerx/1.10/README.md
Updated better overview for installation including a quick start
> Updated beakerx-0.9.1 installation with quickstart

- flink/1.10/README.md
To describe solution of installation Flink via local universe repo without internet connection.
Issue ref: #267
> Add instructions to deploy Flink from local universe without internet access

- ethereum/1.11/README.md
Corresponding Universe PR: https://github.com/mesosphere/universe/pull/2097
> Adding ethereum example

- etcd/1.11/README.md
- etcd/README.md
Example for the new etcd framework (https://github.com/mesosphere/universe/pull/2267)
> Add example for etcd
